services:
# Sonata Admin
    admin.artist:
        class: AppBundle\Admin\ArtistAdmin
        arguments: [ ~ , AppBundle\Entity\Artist, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Artist", group: "Artist" }
